/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * BackendEntryPoint
 * API for managing users, tracks, and projects for a code evaluation platform.
 * OpenAPI spec version: 1.0.0
 */

export interface TrackProgression {
  projects: string[];
  stepDescription: string;
  stepName: string;
  stepStatus: string;
}
