/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * BackendEntryPoint
 * API for managing users, tracks, and projects for a code evaluation platform.
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfile } from './userProfile';

export interface User {
  /** Email address of the user */
  email: string;
  /** GitHub identifier associated with the user */
  github_ID?: string;
  /** A JSON object containing user profile details */
  profile?: UserProfile;
  /** Unique identifier for the user assigned by Cognito */
  sub: string;
}
